TOOLBASE = Kinship  KinshipX  MathCholesky  MathDeriv  MathFloatVector  MathGenMin  MathGold  MathNormal MathSVD  TraitTransformations

HDRONLY = Rmath.h

PARENT_MAKE = Makefile.extlib
include ../Makefile.inc
